name: Build (Fabric 1.21.1 / Java 21)
on:
  push: { branches: [ main, master ] }
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 21 }
      - uses: gradle/gradle-build-action@v3
        with: { gradle-version: 8.10.2, arguments: "build --no-daemon --refresh-dependencies --warning-mode all --stacktrace --info" }
      - uses: actions/upload-artifact@v4
        with: { name: trinkets-sync-redis, path: "build/libs/*.jar" }
